// Generated by CoffeeScript 1.10.0
(function() {
  var Blackjack,
    slice = [].slice;

  module.exports = Blackjack = (function() {
    function Blackjack() {}

    exports.unconvertedAces = false;

    Blackjack.prototype.welcome = function() {
      return console.log("Welcome to the Blackjack Table");
    };

    Blackjack.prototype.dealCard = function() {
      var cards, deck1, deck2, deck3, deck4, deck5, deck6;
      deck1 = [2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11];
      deck2 = deck1;
      deck3 = deck1;
      deck4 = deck1;
      deck5 = deck1;
      deck6 = deck1;
      cards = slice.call(deck1).concat(slice.call(deck2), slice.call(deck3), slice.call(deck4), slice.call(deck5), slice.call(deck6));
      return cards[Math.floor(Math.random() * cards.length)];
    };

    Blackjack.prototype.displayCards = function(card1, card2) {
      var ace, cardTotal, tenCards;
      if (card1 === 11 || card2 === 11) {
        exports.unconvertedAces = true;
      }
      if (card1 !== 11 && card2 !== 11) {
        cardTotal = card1 + card2;
      }
      if (card1 === 11 && card2 !== 11) {
        cardTotal = (card1 + card2) + " or " + (1 + card2);
      }
      if (card1 !== 11 && card2 === 11) {
        cardTotal = (card1 + card2) + " or " + (1 + card1);
      }
      if (card1 === 11 && card2 === 11) {
        cardTotal = 2 + " or " + 12;
      }
      tenCards = ["10", "Jack", "Queen", "King"];
      ace = "Ace";
      if (card1 === 10) {
        card1 = tenCards[Math.floor(Math.random() * tenCards.length)];
      }
      if (card2 === 10) {
        card2 = tenCards[Math.floor(Math.random() * tenCards.length)];
      }
      if (card1 === 11) {
        card1 = ace;
      }
      if (card2 === 11) {
        card2 = ace;
      }
      console.log("You were dealt a(n) " + card1 + " and a(n) " + card2);
      return console.log("Your card total is " + cardTotal);
    };

    Blackjack.prototype.runner = function() {
      this.welcome();
      this.displayCards(this.dealCard(), this.dealCard());
      return console.log(exports.unconvertedAces);
    };

    return Blackjack;

  })();

}).call(this);
